spring.application.name=FitTrack

management.endpoints.web.base-path=/actuator
server.port=8080

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always



spring.datasource.url=jdbc:mysql://localhost:3306/fittrack
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
info.app.name=FitTrack


management.info.env.enabled=true

info.app.version=1.0.0
info.app.description=Fitness Tracking Application
info.company=MbemX