spring.application.name=FitTrack

management.endpoints.web.base-path=/actuator
server.port=8080

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


spring.datasource.url=jdbc:postgresql://bkqrktmberzob4wbsvxi-postgresql.services.clever-cloud.com:50013/bkqrktmberzob4wbsvxi

spring.datasource.username=ui5wosdjkvs0rzttmvfa

spring.datasource.password=DEYSFIkZ8cqIfDiIkLtCtPJm2o0hVU

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

management.info.env.enabled=true

info.app.version=1.0.0
info.app.description=Fitness Tracking Application
info.company=MbemX